language: generic

# Можно тестировать только на одной платформе (в данном случае выбрано osx, clang-3.8)

matrix:
  include:
    #- os: linux
      #sudo: required
      #env: COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5
      #addons:
        #apt:
          #packages:
            #- g++-5
            #- cmake
          #sources: &sources
            #- llvm-toolchain-precise
            #- ubuntu-toolchain-r-test
    - os: osx
      compiler: clang-3.8
      env: COMPILER="clang++-3.8" -std=c++11 OPENSSL_ROOT_DIR="/usr/local/opt/openssl"

env:
  global:
    - secure: "Qxv4DzZZ+NAniw9Lxv5FUm9A35b2OEGdiUDMnSr94OLxAWlAvvtZ5cKdnvk+97JIFGDtPryz45JTGyZY7lyiL8wVPXADf9S7pIK4GjzspOlzQOnm4XepM5UO3BIfXVV5Zld7aqLRtlj0bDtvfZzE04FvZD3HNuG8eC+PnQMfrptG3AHpzT96Yxe2Ef733JrnTZ/0WV2uM1slqkDIHm3rp/UAEYE1U5dOcw0a4OhnccPdOHuf/eNLlsQkGhLbN0V/e0sWkL5j/Eoex7jxZnvLGJ+Qyfspn0yBEJgXXFcWcwmrhQprCUFcjbrBoaGtiXkTHaPjXSKU5zyJobAn22K55VoNezK+A+JzTGudEbh5+UqBPcjZHaexwQNxz7+GNo8haZajpuF5K5kE6i3/IoI8OkfI38XFt9Lfcq4KQz1AblcQqO2EQukzHEXr3ivDgmwL08gm2mx4l8oPjM5YxZGw0Y6RZvSxVgDYRCDXi9O3Hf9oJ7+pHXvoisof57seaipbyBIkQIRw69PD/u/aX5Azf9MlHLsXj06pIMzUkFBI9DibLJz+RQUGsz0dfAM2kh3hRHFB1Xg9QnPpQ3aMgoX9Ncl7l+CsX6iVe9w9O56SFEn079Y+Hcd+Mgd+UJCqUU3ApdMz/hWdIHrT39xObBLnRvK3nPS3y3+a6OWgqAjTTTY="
    - secure: "wnv8/Ggx8wWrQW5pnMWwmV8SM1YZq/QIyFQxQSkxBdYltFUyaP3T13rVo3XJtj0Y1eARjiP/ww7ogfBTfZe36yoITcxq5lk/9j1cdThhN+EFljzy0jixkGcg29ySKPZBcXYOHGpns6ZOIANAKy5GolqKDsckt4w8G9QiFcddTNOwJGYOAoGLj699ZVANisbAQqYOhL4I39e7iG0bMq0gYbAYBuqAljR1YEuFiK1J0kpL229vkM9XZdSQNoVXRwQiTQHSMDn4YJaAEvRJNHep/N8yNGeFW0s3MBW2YuBrGonZixcUNU2XkWDpqJDV8mN7WAL15l++myFuS9V9DFXZPVK1nD+6VkeU77q+8pv5lotnAhS5Gcbe13BG7XEzosbktiGi6fP0ovQ1qGq6uu6duHVXZeA5QWjJEUS++ota8TbNX387F/yR4e08Fiz6LrbC7+GCBA+z3qqklgoytSFN1xFJc078AsBR485EO6o/zAMEV9nqmQZ+/bKLXSlrsuizFSmETG/o5YPF4mNDbgn3Ilen+oCRnWchZvjeK/QelAbp1wBlJDku1P6GZwQ7ZtJBCszLbi/AVLXpjPJPzba9MSsTSl73Wi3FkueZP1FIvmsC0axKY3uv5ZrLM6K5u06J5zVN5nMFmWMTmo0onO/XCMFYBXyOfCBsnlAqR9u7nUw="

script:
  - mkdir build && cd build
  - cmake .. && make
  - ./check -s -r compact