language: generic

# Можно тестировать только на одной платформе (в данном случае выбрано linux, gcc-5)

matrix:
  include:
    - os: linux
      sudo: required
      env: COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5
      addons:
        apt:
          packages:
            - g++-5
            - cmake
          sources: &sources
            - llvm-toolchain-precise
            - ubuntu-toolchain-r-test
    #- os: osx
      #compiler: clang-3.8
      #env: COMPILER="clang++-3.8" -std=c++11 OPENSSL_ROOT_DIR="/usr/local/opt/openssl"

env:
  global:
    - secure: "Er94vimoKcmGQH30t8wj0aBscwO4C3gdo5zwfAQrjXAkPGyisgI4Nh5KZ7z1quYG1O+WKfsSXVwQAsCU3yraBqppRdWpPgoUZEDlvDBHHca1ofSQryJawhzrL8fga8yF64mNvQcyVoZrhM9dNWK+TmeLgeHvEd5owdeM0RI4dAkWMoW2jJ8BnDQq7KR4wnovI1cv/snM5R1cDNEDyddWqilBcfIXwPdZvALsYRRVMCz61Q6bLtmHNi5hzrKTxp3bWZrbhNphbZX7/czejnQUUbT0ZZIbQulNyRmICcYdFuYQu9U0dDF48G5JCXimUa+YyxhY1CLE5Z28AWx26QvCPwNaCbKvcwOOC8qfDhZG1xYVoCUpuFwwB4IJ+kqjoPsfxNvFDpk4g7JHzZreFM8OviHovnKtHRzE3oDxir8rktXRM2glTuhwklJNhsM1ktB7O/EicSu+q20DK56Ax75UhS1pMQ6m9nhrgN7KPBHTiLfpAVVgWArqdFg7fG/iuz+s9BtVMp6Q9FClr6ESjCe/6TiYaWdtnMpZa2+E/aauxfBRrzc4hGOrEItffmmNjIdICes8GWdywAq2KK5bJIqk+tsx9+ncjxSTOK/iKeGmta66t1l1U/wMgO+F73GhN2vPlmBDRqn3Bm+ZoeUKDc45KrlbBED6tFtcRo0FcoEJXkU="
    - secure: "Kz+4XlA2PDjILShY25Jo7UWd5ZCrgTADcDImTKur74bPhyyiX/byw8O/rkVXGQHQ/M8VNEJVH9b5euNZhsOqYpLGZ6xlsl+RE0g9RMiCu3KoboRhqmrycFJvVDP9K63r1eGWbwHJ076/HzTxrDLeWCKmBpLP4tHpMod1EEtKmyZTjFtTZ5yx/Y4v+2+J3VCFF4G9YCCk1CU1pxgHnXoSDivhj6SAxqZU/Chvkb2A/rf71RioKtUsUhi+PbdHo+syCD018OfkGCPJhwgWTQGRySBuC3a1YjDVIIV/ZM3VwFf+GMIAWCZhPslrqHnZHqJuW38ZBKcikJDeKXhy7YTjz4nbHdEm39GyXv4AGu31kJsFgj5/X1nQETVkfEzHcAl2hiXsol+1dshsoX7jwbxsi956AysNpUYocqdx/dCKlZeC0mPMBJMuJWFeOuLFEVTz7pzfneDRmacyT4GOEHH1+wqF4PMLca3jhyuHxg16faSMDJivAwfqebMnr9fEBtWuiWYxiYss8CD3UzMVXca6oVq9hUyXOJoOc3FSLN83p+wMN6hgrUXDAhFTqJkPNc0QWGfu9KGbQ4vceLf2dtz9zmVziW0bsAX8DHpjDxChMHpdVf1tsNedWGsUtkS5RQUU1HsH2zlqobEuFcwcwtm8iuuWO7mVmZevhrihR39BKLw="

script:
  - mkdir build && cd build
  - cmake .. -DOPENSSL_ROOT_DIR=/usr/local/ssl -DOPENSSL_LIBRARIES=/usr/local/ssl/lib && make
  - ./check -s -r compact
