language: generic

# Можно тестировать только на одной платформе (в данном случае выбрано osx, clang-3.8)

matrix:
  include:
    #- os: linux
      #sudo: required
      #env: COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5
      #addons:
        #apt:
          #packages:
            #- g++-5
            #- cmake
          #sources: &sources
            #- llvm-toolchain-precise
            #- ubuntu-toolchain-r-test
    - os: osx
      compiler: clang-3.8
      env: COMPILER="clang++-3.8" -std=c++11 OPENSSL_ROOT_DIR="/usr/local/opt/openssl"

env:
  global:
    # CL_SECRET
    - secure: "IMDkc93K8x/jwIIRl+pNW6mQLGlRlvOHVvXrsMpFgIdx5bGO4Gq3JXM+5okO5+Vd1f+Wfco4KFRnIGoMGxAwpenfN5gE+q33gWyYAr7ebM5VeUXd/l+dn89sARAP6Imd2dcV/E9/99+PYvcK6D/CRNeo3VYGuq9FNEq0D86WKTzRmfNtf7q8jWfd3NX2eFKm9UQm6xSQT1TCjAtW8BEgFrkz6MKyEfku8SWDzdDOIAA4Mggt6Jq2rfwvPn0y1wVRAMUgMmGiWdAORMduZ8sNO9CXG+mCBSIQo48X0XWujKEdIgLSwNgOjyXBdshf5AqY4ciMuwAPYOMOwGesc70/XJ4rnfJ+C+sdjpZ7MM3PWCG3ft1RsuEjT4I6qUeS1G96KPpZxFLnXqY+DKxM7Yx/fYE8aqHUyXAaa6ApOWUrLgVhGliUUSVZuUfQfEXOkfeLXU5ypjXg052JdtWDITZFCjLT0YeVe7W5aHXnamMhVspZXm3Tfs3ynfO9forpiSvIUm02s8WHSHvNBojpChPtqk2UAP8DVd/CrlnHyOKm3chgqoJPB+pjefgqWVtBBDILP/ojUkSKmlG2y2hKYYghDqbpqJg0RUjrF85bQnluWwJjiAGyLj7O7F2ERlH/2LNKwLcb//R30tczsDkO8lrd5CTTTwWHpwdfGRJ+E0miL7M="
    # VALID_CODE
    - secure: "YBKej5ur9c2aTZT69JJRZaYG66aOnLASM2+NwtTJiEF5fbeKQJ0SuR3wXJtI6T0UywroJJeeREVLorBFNoya73l6M7lVZQlSzl+r938FOvBZ5JyN8/Xc7dzK3bDljr9KIf/fV26zBNGJWrFtFdZ0+lZkGynGmC8pucIneABape3z1pWktGYONL3+snNcXJoXHld8KIkl2mjauLgaCy5yr5kkkgT+T7hhWdXj983ohFEwJwFg/7cax+kTdCrXj/iPUdqiDMpUyVd+8Jt+l78tIUHHaGte2M4ehslmBy20ZnP3nQ3sQezs3VhScoRKRfyWJgv/ZK+bjaGfA3XFkSNRSbqJfy0VC14ZI4PQnNtbqE7mghTlp4Tro5CQxK4FbAu1X7UBXdr1yjPE+WCbdBg/4ZdrwnrR1YGuZ9eGkgSZjGkDLyd7UPU8XLhKrWGjDpCMisGjetAzs/I2B5RH3sd9al43C3GvWrb8wZQ7975VeSsjFuInFRwLDV7E+diXKus3xbhB0TkAkv5c9bmwTsZrPB+msfoG9H4RtaGEFjdfIQebFoXn+qO6lEEIMvAfLJ1UayXp0AEWn8yFyiu7U228eMn46V5fhyseclhhNCrlC0bbseYBerajVWyxP4MyNEP639MVtJPzw+yvTA5beVxnAfcwvhvOBicPkeQARIzARIQ="

script:
  - mkdir build && cd build
  - cmake .. -DOPENSSL_ROOT_DIR=/usr/local/ssl -DOPENSSL_LIBRARIES=/usr/local/ssl/lib && make
  - ./check -s -r compact