language: generic

matrix:
  include:
    - os: linux
      sudo: required
      env: COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5
      addons:
        apt:
          packages:
            - g++-5
            - cmake
          sources: &sources
            - llvm-toolchain-precise
            - ubuntu-toolchain-r-test
    - os: osx
      compiler: clang-3.8
      env: COMPILER="clang++-3.8" -std=c++11 OPENSSL_ROOT_DIR="/usr/local/opt/openssl"

env:
  global:
    # CL_SECRET
    - secure: "IMDkc93K8x/jwIIRl+pNW6mQLGlRlvOHVvXrsMpFgIdx5bGO4Gq3JXM+5okO5+Vd1f+Wfco4KFRnIGoMGxAwpenfN5gE+q33gWyYAr7ebM5VeUXd/l+dn89sARAP6Imd2dcV/E9/99+PYvcK6D/CRNeo3VYGuq9FNEq0D86WKTzRmfNtf7q8jWfd3NX2eFKm9UQm6xSQT1TCjAtW8BEgFrkz6MKyEfku8SWDzdDOIAA4Mggt6Jq2rfwvPn0y1wVRAMUgMmGiWdAORMduZ8sNO9CXG+mCBSIQo48X0XWujKEdIgLSwNgOjyXBdshf5AqY4ciMuwAPYOMOwGesc70/XJ4rnfJ+C+sdjpZ7MM3PWCG3ft1RsuEjT4I6qUeS1G96KPpZxFLnXqY+DKxM7Yx/fYE8aqHUyXAaa6ApOWUrLgVhGliUUSVZuUfQfEXOkfeLXU5ypjXg052JdtWDITZFCjLT0YeVe7W5aHXnamMhVspZXm3Tfs3ynfO9forpiSvIUm02s8WHSHvNBojpChPtqk2UAP8DVd/CrlnHyOKm3chgqoJPB+pjefgqWVtBBDILP/ojUkSKmlG2y2hKYYghDqbpqJg0RUjrF85bQnluWwJjiAGyLj7O7F2ERlH/2LNKwLcb//R30tczsDkO8lrd5CTTTwWHpwdfGRJ+E0miL7M="
    # VALID_CODE
    - secure: "Pp3/4q7EBitawyhBKd4+hS9eD4vVxRPzy64pUEGt7h1kfZc4rHnmFm1AbzFjvKHKpXVKPX5Bnu2HH1N0hsV5rbtY6eCKwuEuD/OTP7AVrPG3B1E+AWUQrylLgyI2zC3/vApFbx/yipdUAzGlfylRXqIWoi5Duv762LaZEVIIERv61OwuIFe43Sg2G5dwyPUEgL3C46sSWqCGVx3BI+Q0x1d6DkIVn8tpLy4gmZvZLVgibAy+1Yf6LjD4keBIzMG6RxmpzWEEdA8WlZLB9n3miW3MLJAZUH/vlCWPCKnkicghR8Kly09SjKi+hRnh2wS7jSAOKBgyr6ObTQtRlGI3smul+BvfHGzwVNbr+b0Z18hsQVl1Q1TTM9ECJKao3mJ9KbDyCg81d80Jnks4LqALEj5KIeDbEDSKqNe7atbZBZ0USVFQ3dlfqYNIhK1AflA1TSqA4IJcpG4YNgKT13JhIKow3T3LGg1s7EQcZJ5BbNOo5TnYaFAasHPf7Y5G1IjGcFn95DzIwFg15zq8i9F9uMUriqrCRqZ5MYMHadacrsx+6f+Ko80uLzWXuAwjosuMtnMu1FnsW0H5laaDycINSDE+tluqCVuYCcPxTjO3sTWVtvlay/FnMa/aZKibirx/6QfP37rsmQWHKZu7opY241pGfes7mEB7b1ZKFjPn9MM="

script:
  - mkdir build && cd build
  - cmake .. -DOPENSSL_ROOT_DIR=/usr/local/ssl -DOPENSSL_LIBRARIES=/usr/local/ssl/lib && make
  # Можно выполнять только на одной ОС
  #- ./check -s -r compact
