language: generic

# Можно тестировать только на одной платформе (в данном случае выбрано osx, clang-3.8)

matrix:
  include:
    - os: linux
      sudo: required
      env: COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5
      addons:
        apt:
          packages:
            - g++-5
            - cmake
          sources: &sources
            - llvm-toolchain-precise
            - ubuntu-toolchain-r-test
    #- os: osx
      #compiler: clang-3.8
      #env: COMPILER="clang++-3.8" -std=c++11 OPENSSL_ROOT_DIR="/usr/local/opt/openssl"

env:
  global:
    - secure: "O9H+bDuxdq0OXbIaYrwsqyXk6a5V3JgBMg7KELVYrq0pCl4d/w4xAvSSJfCrFeC7kgXsxXE52pxqCsydqH3J2sjiaymf1mAXGFnR+AYem7wVwJd9pvStNT4e1ek5IsjAkD/sUnDWwLLIYNhTPUyvVIfd1apBynYrAnrDYPYxFKYPwlGG8YCM58xK9XdzeifirzagCh+6Mbuhmu8iwUhNM3gfD1A8bPXhCCuYYpE0wV8C6Dmsat0uxRLYC0XfiZGXW4kxi5NRcVSEGE2R9X1kCr7K8UBJm2CUomqa75G0MmHuXgW9ECvDCABGK1r9BWUUmZtaI9Vdh+aylmqALYizeC2Z+HgSMpiSe6+WhRZClkRzkSBe2d5apoCJ4HFzOPzTW/JwNHeGFfFHXVU1f6EMAjqsCWoXewX/MD8Q+Nen2zUFClmE/PgKeRMtq8+Tog60BIJ3ogtF0TMrOs8uK6LO+7FBwfoF3Vf0zQQ5jo9HYCElPEA6f4EC6g2rYmus4KtvYJxab0eMH4hpRkvdBCwwFDLPN+b4Ul/287cnuGBZRORmBODa04sqn6byGv5lKDMNTqQQftj2joJFZDdJWXAEof5OAzhbf2Sr0Sypu9bYzkzKroxcNKXORlZhcOQ2U4yVm/OAbhB0vnaHPbm00azXRByGnCDkg2xtjYCWpdSH6yU="
    - secure: "PqY1x37tzuxQOGuqAJ6LFMfKIdBeuns/sSGb2PD0BhwcvOCS8n7XnL9YTJ/MAJVvzNc7L4iAkTOBUd2WtFhv6bOqjZZBouiZyg54iMRlZJ32Duh7ysTZT6fXjTgKrlG5HwFPAagHp3/c5Kyw+MXE4vfCd1QZL1olnwx13bPxmNoDb4utSLFRcV25HkOcji3MBb6C/nKURtjbByLaLQuVahQBFMeka7pk5omqz2RQXitJfw9KqqriA/bkOMFavYwsFUpGrLTyXcs9ZGtS/ZpFA3ITWhTehvwqA7K4lO5cDPcNG47XPzbrO8YB4xlgLc+JZI9BLcjzvjTPvWTH+Z26lVPd4J8fYKJifPNKBdjDCV+0pkz1JnwmagWPbrJOOco+j4JUjPZ8A2m2cyx/NYv92bu8p0sxGEyzx0e9mRlqTNQtap/XBbZmVKSYXmJzdhpEr+3x2lQnMB5XUtAp0jyJYoy/+WPFawb8qlQ4+ZeBx7Vd51RnIv2xsWU+BWMiKX9NBDhOdJ8XRIv8UsnJDOEKdcG6qInvphLhk8CYq6rNNrP3+KLpvomfiBjyZnmPOqqIAAToUaIpHG48mzCxwZDDDAYk/JCk6+wpBxPRTkcZeAXSvO6rVTcQ5CckgyXSd61orxPjAT6wYBvlKGS8zWLiqNgfsJwCtHdxpWoS93U+AsU="

script:
  - mkdir build && cd build
  - cmake .. -DOPENSSL_ROOT_DIR=/usr/local/ssl -DOPENSSL_LIBRARIES=/usr/local/ssl/lib && make
  - ./check -s -r compact
